//! The hostile file corpus: generated at test time, committed nowhere.
//!
//! Every file here is synthetic and built from code. **No hostile file is
//! committed**; only this generator and a hash manifest
//! (`fixtures/hostile/MANIFEST.json`, at the repository's root) are. The first
//! test regenerates each file into a temporary folder and puts it through the
//! intake exactly as the Documents page does; the second regenerates them and
//! checks their SHA-256 against the committed manifest, so a generator that
//! drifts is a failure and a missing manifest is never a skip. After a
//! deliberate change to a case, rewrite the manifest with
//! `cargo test -- --ignored bless_hostile_manifest`.
//!
//! The "executable" is a **non-PE stub** — an `MZ` signature and an ASCII
//! marker, never a program. The zip bomb is generated by **streaming** zeros to
//! the compressor, so the generator never holds the inflated size.
//!
//! Each case says what the intake must do with it: refuse it with a sentence
//! that names the file and contains the given words — and write nothing — or
//! keep it as the type its bytes are, whatever its name says.
//!
//! This is the pattern of the sibling product's corpus (a generator, a
//! manifest, a `bless` test); it lives inside the crate rather than in
//! `tests/`, because an integration test binary links the whole of Tauri once
//! more for no gain.

use std::io::{Cursor, Write};

use flate2::write::DeflateEncoder;
use flate2::{Compression, Crc};
use image::ImageFormat;

use crate::files::intake::{sha256_hex, Format};

/// What the intake must do with a case.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Expect {
    /// Refused, the sentence naming the file and containing these words.
    Refused(&'static str),
    /// Kept, as this type.
    Kept(Format),
}

/// One file of the corpus.
pub struct Case {
    /// Its name, as a person would have chosen it.
    pub name: &'static str,
    /// What the intake must do with it.
    pub expect: Expect,
    /// Its bytes, built from code.
    pub generate: fn() -> Vec<u8>,
}

/// Every case, in the order the plan lists them.
pub fn cases() -> Vec<Case> {
    vec![
        Case {
            name: "lie.jpg",
            expect: Expect::Refused("Ridgebeam keeps photos and PDFs, and this is neither"),
            generate: text_named_jpg,
        },
        Case {
            name: "huge.png",
            expect: Expect::Refused("larger than 12 000 × 12 000 pixels"),
            generate: lying_png,
        },
        Case {
            name: "cut.jpg",
            expect: Expect::Refused("its header could not be read"),
            generate: truncated_jpeg,
        },
        Case {
            name: "empty.jpg",
            expect: Expect::Refused("it is empty"),
            generate: Vec::new,
        },
        Case {
            name: "big.jpg",
            expect: Expect::Refused("larger than 25 MiB"),
            generate: too_large,
        },
        Case {
            name: "big.pdf",
            expect: Expect::Refused("larger than 25 MiB"),
            generate: too_large_pdf,
        },
        Case {
            name: "drawing.pdf",
            expect: Expect::Kept(Format::Png),
            generate: png_named_pdf,
        },
        Case {
            name: "setup.pdf",
            expect: Expect::Refused("Ridgebeam keeps photos and PDFs, and this is neither"),
            generate: executable_stub,
        },
        Case {
            name: "zero-width.png",
            expect: Expect::Refused("the file may be damaged"),
            generate: zero_width_png,
        },
        Case {
            name: "lying.webp",
            expect: Expect::Refused("larger than 12 000 × 12 000 pixels"),
            generate: lying_webp,
        },
        Case {
            name: "IMG_0001.heic",
            expect: Expect::Refused("HEIC"),
            generate: heic,
        },
        Case {
            name: "drawing.svg",
            expect: Expect::Refused("SVG drawing, which can carry scripts"),
            generate: svg,
        },
        Case {
            name: "bomb.pdf",
            expect: Expect::Refused("Ridgebeam keeps photos and PDFs, and this is neither"),
            generate: zip_bomb,
        },
    ]
}

/// The manifest: every case's name, size and SHA-256, as committed.
pub fn manifest_json() -> String {
    let fixtures: Vec<serde_json::Value> = cases()
        .iter()
        .map(|case| {
            let bytes = (case.generate)();
            // Keys written in alphabetical order, so the text is the same
            // whether or not serde_json keeps insertion order in this build.
            serde_json::json!({
                "bytes": bytes.len(),
                "file": case.name,
                "sha256": sha256_hex(&bytes),
            })
        })
        .collect();
    let mut text = serde_json::to_string_pretty(&serde_json::json!({ "fixtures": fixtures }))
        .expect("a manifest is JSON");
    text.push('\n');
    text
}

/// The CRC a PNG chunk carries.
pub fn crc32(bytes: &[u8]) -> u32 {
    let mut crc = 0xFFFF_FFFFu32;
    for byte in bytes {
        crc ^= u32::from(*byte);
        for _ in 0..8 {
            crc = if crc & 1 == 1 {
                (crc >> 1) ^ 0xEDB8_8320
            } else {
                crc >> 1
            };
        }
    }
    !crc
}

/// A PNG chunk: length, type, data, CRC.
fn chunk(kind: &[u8; 4], data: &[u8]) -> Vec<u8> {
    let mut out = (data.len() as u32).to_be_bytes().to_vec();
    let body = [kind.as_slice(), data].concat();
    out.extend_from_slice(&body);
    out.extend_from_slice(&crc32(&body).to_be_bytes());
    out
}

/// A well-formed PNG whose only lie is its size in the header.
fn png_with_header(width: u32, height: u32) -> Vec<u8> {
    let mut png = vec![0x89, b'P', b'N', b'G', 0x0D, 0x0A, 0x1A, 0x0A];
    let mut ihdr = Vec::new();
    ihdr.extend_from_slice(&width.to_be_bytes());
    ihdr.extend_from_slice(&height.to_be_bytes());
    ihdr.extend_from_slice(&[8, 2, 0, 0, 0]);
    png.extend(chunk(b"IHDR", &ihdr));
    png.extend(chunk(
        b"IDAT",
        &[0x78, 0x9C, 0x03, 0x00, 0x00, 0x00, 0x00, 0x01],
    ));
    png.extend(chunk(b"IEND", &[]));
    png
}

fn real_png(width: u32, height: u32) -> Vec<u8> {
    let image = image::RgbImage::from_pixel(width, height, image::Rgb([200, 120, 40]));
    let mut bytes = Vec::new();
    image
        .write_to(&mut Cursor::new(&mut bytes), ImageFormat::Png)
        .expect("a PNG");
    bytes
}

fn text_named_jpg() -> Vec<u8> {
    b"This is a text file. It has a photo's name and nothing else.".to_vec()
}

fn lying_png() -> Vec<u8> {
    png_with_header(100_000, 100_000)
}

/// A real JPEG, cut off inside its first segment: it starts like a JPEG and
/// has no frame header to read a size from.
fn truncated_jpeg() -> Vec<u8> {
    let image = image::RgbImage::from_pixel(64, 48, image::Rgb([40, 120, 200]));
    let mut bytes = Vec::new();
    image::codecs::jpeg::JpegEncoder::new_with_quality(&mut bytes, 90)
        .encode_image(&image)
        .expect("a JPEG");
    bytes.truncate(20);
    bytes
}

/// 26 MiB, past the 25 MiB cap: refused from its size alone.
fn too_large() -> Vec<u8> {
    vec![0u8; 26 * 1024 * 1024]
}

/// A PDF whose header is right and which is 26 MiB.
fn too_large_pdf() -> Vec<u8> {
    let mut bytes = b"%PDF-1.7\n%".to_vec();
    bytes.resize(26 * 1024 * 1024, b' ');
    bytes.extend_from_slice(b"\n%%EOF\n");
    bytes
}

/// A PNG someone named `.pdf`: kept, as the PNG it is.
fn png_named_pdf() -> Vec<u8> {
    real_png(32, 24)
}

/// An `MZ` stub named `.pdf` — a signature and a marker, never a program.
fn executable_stub() -> Vec<u8> {
    let mut bytes = b"MZ".to_vec();
    bytes.resize(64, 0);
    bytes.extend_from_slice(b"This is a synthetic stub for a test. It is not a program.");
    bytes
}

fn zero_width_png() -> Vec<u8> {
    png_with_header(0, 480)
}

/// A WebP whose extended header claims 60 000 × 60 000, followed by the
/// header of a 1 × 1 lossless image. (60 000, not 100 000: the WebP decoder
/// refuses by itself a canvas whose area overflows 32 bits, so a larger lie
/// would never reach the product's own cap — which is what this case holds.)
fn lying_webp() -> Vec<u8> {
    let side: u32 = 60_000 - 1;
    let mut vp8x = vec![0u8; 4];
    vp8x.extend_from_slice(&side.to_le_bytes()[..3]);
    vp8x.extend_from_slice(&side.to_le_bytes()[..3]);
    let vp8l = [0x2f, 0x00, 0x00, 0x00, 0x00, 0x00];
    let mut body = b"WEBP".to_vec();
    for (kind, data) in [(b"VP8X", vp8x.as_slice()), (b"VP8L", vp8l.as_slice())] {
        body.extend_from_slice(kind);
        body.extend_from_slice(&(data.len() as u32).to_le_bytes());
        body.extend_from_slice(data);
        if data.len() % 2 == 1 {
            body.push(0);
        }
    }
    let mut webp = b"RIFF".to_vec();
    webp.extend_from_slice(&(body.len() as u32).to_le_bytes());
    webp.extend(body);
    webp
}

fn heic() -> Vec<u8> {
    let mut bytes = vec![0, 0, 0, 24];
    bytes.extend_from_slice(b"ftypheic");
    bytes.extend_from_slice(&[0; 32]);
    bytes
}

fn svg() -> Vec<u8> {
    b"<?xml version=\"1.0\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"10\" height=\"10\">\n  <script>/* inert, for a test */</script>\n  <rect width=\"10\" height=\"10\"/>\n</svg>\n".to_vec()
}

/// A zip archive whose one entry inflates to 32 MiB of zeros — past the cap —
/// named `.pdf`. Refused by its first bytes; nothing ever inflates it.
fn zip_bomb() -> Vec<u8> {
    const INFLATED: usize = 32 * 1024 * 1024;
    let mut encoder = DeflateEncoder::new(Vec::new(), Compression::default());
    let mut crc = Crc::new();
    let block = vec![0u8; 1024 * 1024];
    for _ in 0..(INFLATED / block.len()) {
        encoder.write_all(&block).expect("deflate");
        crc.update(&block);
    }
    let deflated = encoder.finish().expect("deflate");
    let crc = crc.sum();
    let name = b"zeros.bin";
    let mut zip = Vec::new();
    zip.extend_from_slice(b"PK\x03\x04");
    zip.extend_from_slice(&20u16.to_le_bytes()); // version needed
    zip.extend_from_slice(&0u16.to_le_bytes()); // flags
    zip.extend_from_slice(&8u16.to_le_bytes()); // deflate
    zip.extend_from_slice(&[0, 0, 0x21, 0]); // time, date
    zip.extend_from_slice(&crc.to_le_bytes());
    zip.extend_from_slice(&(deflated.len() as u32).to_le_bytes());
    zip.extend_from_slice(&(INFLATED as u32).to_le_bytes());
    zip.extend_from_slice(&(name.len() as u16).to_le_bytes());
    zip.extend_from_slice(&0u16.to_le_bytes());
    zip.extend_from_slice(name);
    zip.extend_from_slice(&deflated);
    zip
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use super::*;
    use crate::db::testing::Scratch;
    use crate::files::intake::{Accept, CopyIn};

    fn manifest_path() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .expect("the repository root")
            .join("fixtures")
            .join("hostile")
            .join("MANIFEST.json")
    }

    fn files_under(folder: &std::path::Path) -> usize {
        std::fs::read_dir(folder).map(|e| e.count()).unwrap_or(0)
    }

    /// The gate: every case through the intake as the Documents page takes it.
    /// Every case is checked before the test fails, so one run names every case
    /// that does not hold.
    #[test]
    fn every_hostile_file_is_refused_with_a_sentence_naming_it_and_nothing_written() {
        let source = Scratch::create();
        let mut failures = Vec::new();
        for case in cases() {
            let generated = (case.generate)();
            let path = source.path().join(case.name);
            std::fs::write(&path, &generated).expect("the case is written");
            assert_eq!(
                std::fs::read(&path).expect("and read back"),
                generated,
                "{} read back differently",
                case.name
            );
            let work = Scratch::create();
            let mut copy = CopyIn::new(work.path());
            let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                copy.copy(&path, Accept::Documents)
            }));
            let failure = match (result, case.expect) {
                (Err(_), _) => Some(format!("{}: the intake panicked", case.name)),
                (Ok(Err(error)), Expect::Refused(words)) => {
                    drop(copy);
                    let sentence = error.to_string();
                    if error.kind() != "photo_refused" {
                        Some(format!(
                            "{}: refused as {}, not photo_refused",
                            case.name,
                            error.kind()
                        ))
                    } else if !sentence.contains(case.name) || !sentence.contains(words) {
                        Some(format!("{}: the sentence was “{sentence}”", case.name))
                    } else if files_under(work.path()) != 0 {
                        Some(format!("{}: refused, but something was written", case.name))
                    } else {
                        None
                    }
                }
                (Ok(Ok(copied)), Expect::Kept(format)) => {
                    copy.keep();
                    let stored = work.path().join("documents").join(format!(
                        "{}.{}",
                        copied.hash,
                        format.extension()
                    ));
                    if copied.format != format {
                        Some(format!(
                            "{}: kept as {:?}, not {format:?}",
                            case.name, copied.format
                        ))
                    } else if copied.file_name != case.name || !stored.is_file() {
                        Some(format!(
                            "{}: not kept under its hash with its type's extension",
                            case.name
                        ))
                    } else {
                        None
                    }
                }
                (Ok(Ok(_)), Expect::Refused(_)) => {
                    Some(format!("{}: kept, but must be refused", case.name))
                }
                (Ok(Err(error)), Expect::Kept(_)) => Some(format!(
                    "{}: refused ({error}), but must be kept",
                    case.name
                )),
            };
            failures.extend(failure);
        }
        assert!(
            failures.is_empty(),
            "{} case(s) did not hold:\n{}",
            failures.len(),
            failures.join("\n")
        );
    }

    /// A diary photo or an answer's photo takes images only: a PDF there is
    /// refused, and the sentence says where it belongs.
    #[test]
    fn a_pdf_offered_as_a_photo_is_refused_and_sent_to_the_documents_page() {
        let source = Scratch::create();
        let work = Scratch::create();
        let path = source.path().join("permit.pdf");
        std::fs::write(&path, b"%PDF-1.4\n%%EOF\n").unwrap();

        let refused = CopyIn::new(work.path())
            .copy(&path, Accept::Images)
            .unwrap_err();

        assert_eq!(
            refused.to_string(),
            "“permit.pdf” was not added: it is a PDF, not a photo — add it on the Documents page."
        );
        assert_eq!(files_under(work.path()), 0);
    }

    #[test]
    fn the_manifest_matches_the_generator() {
        let committed = std::fs::read_to_string(manifest_path()).unwrap_or_else(|_| {
            panic!(
                "the hostile manifest is missing at {}; write it with `cargo test -- --ignored bless_hostile_manifest`",
                manifest_path().display()
            )
        });
        assert_eq!(
            committed.replace("\r\n", "\n"),
            manifest_json(),
            "the hostile corpus generator drifted from its committed manifest"
        );
    }

    /// Write the manifest from the current generator. Not part of `cargo test`;
    /// run it by name after a deliberate change to a case.
    #[test]
    #[ignore]
    fn bless_hostile_manifest() {
        let path = manifest_path();
        std::fs::create_dir_all(path.parent().expect("a parent")).expect("the fixtures folder");
        std::fs::write(&path, manifest_json()).expect("the manifest is written");
        println!("wrote {}", path.display());
    }
}
